%Case 1
rf=0.1;
simopt = simset('solver','ode23tb','SrcWorkspace','Current','DstWorkspace','Current');  % Initialize sim options
[tout,xout,yout] = sim('LineFaultModel1',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x1=[VEa VEb VEc IEa IEb IEc V0 I0]
t1=[0 0 0 0]
[tout,xout,yout] = sim('LineFaultModel1ag',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x2=[VEa VEb VEc IEa IEb IEc V0 I0]
t2=[1 0 0 1]
[tout,xout,yout] = sim('LineFaultModel1bg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x3=[VEa VEb VEc IEa IEb IEc V0 I0]
t3=[0 1 0 1]
[tout,xout,yout] = sim('LineFaultModel1cg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x4=[VEa VEb VEc IEa IEb IEc V0 I0]
t4=[0 0 1 1]
[tout,xout,yout] = sim('LineFaultModel1abg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x5=[VEa VEb VEc IEa IEb IEc V0 I0]
t5=[1 1 0 1]
[tout,xout,yout] = sim('LineFaultModel1acg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x6=[VEa VEb VEc IEa IEb IEc V0 I0]
t6=[1 0 1 1]
[tout,xout,yout] = sim('LineFaultModel1bcg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x7=[VEa VEb VEc IEa IEb IEc V0 I0]
t7=[0 1 1 1]
[tout,xout,yout] = sim('LineFaultModel1abcg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x8=[VEa VEb VEc IEa IEb IEc V0 I0]
t8=[1 1 1 1]
[tout,xout,yout] = sim('LineFaultModel1abc',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x9=[VEa VEb VEc IEa IEb IEc V0 I0]
t9=[1 1 1 0]
[tout,xout,yout] = sim('LineFaultModel1ab',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x10=[VEa VEb VEc IEa IEb IEc V0 I0]
t10=[1 1 0 0];
[tout,xout,yout] = sim('LineFaultModel1ac',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x11=[VEa VEb VEc IEa IEb IEc V0 I0]
t11=[1 0 1 0]
[tout,xout,yout] = sim('LineFaultModel1bc',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x12=[VEa VEb VEc IEa IEb IEc V0 I0]
t12=[0 1 1 0]
data=[x1;x2;x3;x4;x5;x6;x7;x8;x9;x10;x11;x12]
t=[t1;t2;t3;t4;t5;t6;t7;t8;t9;t10;t11;t12]

%Case 2
rf=10;
simopt = simset('solver','ode23tb','SrcWorkspace','Current','DstWorkspace','Current');  % Initialize sim options
[tout,xout,yout] = sim('LineFaultModel1ag',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x2=[VEa VEb VEc IEa IEb IEc V0 I0]
t2=[1 0 0 1]
[tout,xout,yout] = sim('LineFaultModel1bg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x3=[VEa VEb VEc IEa IEb IEc V0 I0]
t3=[0 1 0 1]
[tout,xout,yout] = sim('LineFaultModel1cg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x4=[VEa VEb VEc IEa IEb IEc V0 I0]
t4=[0 0 1 1]
[tout,xout,yout] = sim('LineFaultModel1abg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x5=[VEa VEb VEc IEa IEb IEc V0 I0]
t5=[1 1 0 1]
[tout,xout,yout] = sim('LineFaultModel1acg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x6=[VEa VEb VEc IEa IEb IEc V0 I0]
t6=[1 0 1 1]
[tout,xout,yout] = sim('LineFaultModel1bcg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x7=[VEa VEb VEc IEa IEb IEc V0 I0]
t7=[0 1 1 1]
[tout,xout,yout] = sim('LineFaultModel1abcg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x8=[VEa VEb VEc IEa IEb IEc V0 I0]
t8=[1 1 1 1]
[tout,xout,yout] = sim('LineFaultModel1abc',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x9=[VEa VEb VEc IEa IEb IEc V0 I0]
t9=[1 1 1 0]
[tout,xout,yout] = sim('LineFaultModel1ab',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x10=[VEa VEb VEc IEa IEb IEc V0 I0]
t10=[1 1 0 0];
[tout,xout,yout] = sim('LineFaultModel1ac',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x11=[VEa VEb VEc IEa IEb IEc V0 I0]
t11=[1 0 1 0]
[tout,xout,yout] = sim('LineFaultModel1bc',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x12=[VEa VEb VEc IEa IEb IEc V0 I0]
t12=[0 1 1 0]
data1=[x2;x3;x4;x5;x6;x7;x8;x9;x10;x11;x12;]
ta1=[t2;t3;t4;t5;t6;t7;t8;t9;t10;t11;t12;]
%Case 3
rf=100;
simopt = simset('solver','ode23tb','SrcWorkspace','Current','DstWorkspace','Current');  % Initialize sim options
[tout,xout,yout] = sim('LineFaultModel1ag',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x2=[VEa VEb VEc IEa IEb IEc V0 I0]
t2=[1 0 0 1]
[tout,xout,yout] = sim('LineFaultModel1bg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x3=[VEa VEb VEc IEa IEb IEc V0 I0]
t3=[0 1 0 1]
[tout,xout,yout] = sim('LineFaultModel1cg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x4=[VEa VEb VEc IEa IEb IEc V0 I0]
t4=[0 0 1 1]
[tout,xout,yout] = sim('LineFaultModel1abg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x5=[VEa VEb VEc IEa IEb IEc V0 I0]
t5=[1 1 0 1]
[tout,xout,yout] = sim('LineFaultModel1acg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x6=[VEa VEb VEc IEa IEb IEc V0 I0]
t6=[1 0 1 1]
[tout,xout,yout] = sim('LineFaultModel1bcg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x7=[VEa VEb VEc IEa IEb IEc V0 I0]
t7=[0 1 1 1]
[tout,xout,yout] = sim('LineFaultModel1abcg',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x8=[VEa VEb VEc IEa IEb IEc V0 I0]
t8=[1 1 1 1]
[tout,xout,yout] = sim('LineFaultModel1abc',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x9=[VEa VEb VEc IEa IEb IEc V0 I0]
t9=[1 1 1 0]
[tout,xout,yout] = sim('LineFaultModel1ab',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x10=[VEa VEb VEc IEa IEb IEc V0 I0]
t10=[1 1 0 0];
[tout,xout,yout] = sim('LineFaultModel1ac',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x11=[VEa VEb VEc IEa IEb IEc V0 I0]
t11=[1 0 1 0]
[tout,xout,yout] = sim('LineFaultModel1bc',[0 0.1],simopt);
[C,L] = wavedec(va,10,'db1');
[VEa] = wenergy(C,L);
[C,L] = wavedec(vb,10,'db1');
[VEb] = wenergy(C,L);
[C,L] = wavedec(vc,10,'db1');
[VEc] = wenergy(C,L);
[C,L] = wavedec(ia,10,'db1');
[IEa] = wenergy(C,L);
[C,L] = wavedec(ib,10,'db1');
[IEb] = wenergy(C,L);
[C,L] = wavedec(ic,10,'db1');
[IEc] = wenergy(C,L);
[C,L] = wavedec(v0,10,'db1');
[V0] = wenergy(C,L);
[C,L] = wavedec(i0,10,'db1');
[I0] = wenergy(C,L);
x12=[VEa VEb VEc IEa IEb IEc V0 I0]
t12=[0 1 1 0]
data2=[x2;x3;x4;x5;x6;x7;x8;x9;x10;x11;x12;]
ta2=[t2;t3;t4;t5;t6;t7;t8;t9;t10;t11;t12;]
data3=[data;data1;data2;data;data1;data2;data;data1;data2;data;data1;data2;data;data1;data2;data;data1;data2;data;data1;data2;data;data1;data2;]
ta=[t;ta1;ta2;t;ta1;ta2;t;ta1;ta2;t;ta1;ta2;t;ta1;ta2;t;ta1;ta2;t;ta1;ta2;t;ta1;ta2;]
d=[data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;data3;]
ta4=[ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;ta;]
d=transpose(d)
ta4=transpose(ta4)
nnstart
nftool
% Next follow the Instruction
% Press Next 
% Select Inputs (d)
% Select Target (ta4)
% Press Next
% Press Once again Next
% Type number of neurons equal to 160
% Press Next
% Press Train


